### ISSUE TITLE
Support custom foreground colour for a feed name

### ISSUE THREAD

**Issue by FingerlessGlov3s** [impredicative/irc-rss-feed-bot#16]
It would be cool if you could format the message it sends per feed.

There would be an optional "message-format" variable you can set. Which allows you to customize the message it sends. This can also be used to add colour support etc. Need to see how colours are done in miniirc for that part I'm unsure on.

Config would look something like this
```
host: chat.freenode.net
ssl_port: 6697
nick: MyFeed[bot]
alerts_channel: '##mybot-alerts'
mode:
feeds:
  "#some_chan1":
    j:AJCN:
      url: https://academic.oup.com/rss/site_6122/3981.xml
      period: 24
      message-format: "[{feedname}] {title} -> {url}"
      blacklist:
        title:
          - ^Calendar\ of\ Events$
    MedicalXpress:nutrition:
      url: https://medicalxpress.com/rss-feed/search/?search=nutrition
    r/FoodNerds:
      url: https://www.reddit.com/r/FoodNerds/new/.rss
      shorten: false
      message-format: "{title} -> {url}"
      sub:
        url:
          pattern: ^https://www\.reddit\.com/r/.+?/comments/(?P<id>.+?)/.+$
          repl: https://redd.it/\g<id>
```
