### ISSUE TITLE
user should be allowed to define global defaults

### ISSUE THREAD

**Issue by ssbarnea** [impredicative/irc-rss-feed-bot#32]
Instead of using YAML anchors which are not very easy to understand (or popular) and which do add their own boilerplate, it would be very useful to make defaults configurable.

Example:
```
defaults:
      period: 0.5
      shorten: false
      new: 0
```
Adding something like this would allow users to avoid having to either repeat themselves or use the yaml anchors.
