### ISSUE TITLE
AttributeError: 'types.SimpleNamespace' object has no attribute 'nick_casefold'

### ISSUE THREAD

**Issue by lovelaced** [impredicative/irc-rss-feed-bot#55]
Hi there, thanks for all your work. I'm attempting to run this via a docker-compose file as suggested in the readme. All permissions on config/secrets seem fine, the bot logs in fine with the configured nick and admin, but nothing seems to work and it prints this exception after successful login. Admin commands also do not work (when I type 'exit' it spits out this exception again).

```
irc-rss-feed-bot    | Exception in thread Thread-13:
irc-rss-feed-bot    | Traceback (most recent call last):
irc-rss-feed-bot    |   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
irc-rss-feed-bot    |     self.run()
irc-rss-feed-bot    |   File "/usr/local/lib/python3.8/threading.py", line 870, in run
irc-rss-feed-bot    |     self._target(*self._args, **self._kwargs)
irc-rss-feed-bot    |   File "/app/ircrssfeedbot/bot.py", line 345, in _handle_join
irc-rss-feed-bot    |     if (user.casefold() != config.runtime.nick_casefold) or (channel.casefold() not in config.INSTANCE["channels:casefold"]):
irc-rss-feed-bot    | AttributeError: 'types.SimpleNamespace' object has no attribute 'nick_casefold'
```

Is this a bug or a misconfiguration somehow on my part? Thanks!

**Comment by impredicative** [comment]
Would you mind if I see your full non-secret YAML config?

**Comment by impredicative** [comment]
Basically, `.nick_casefold` is supposed to be set when processing event 900 (RPL_LOGGEDIN) and by event NICK, both of which are received from the IRC server. I don't know which server you're using, but make sure your nick is logged in.

**Comment by lovelaced** [comment]
I do get the confirmation in my server buffer that my nick is logged in and authed to my admin account. ("xxx has just authenticated as you")

```
host: irc.hackint.org
ssl_port: 6697
nick: testbotnick
admin: my!~admin@details
alerts_channel: '#testalertchannel
mode: "+igR"
defaults:
  new: all
feeds:
  "#testalertchannel":
    talks:
      url: https://talks.toorcon.net/toorcon21/schedule/feed.xml
      period: 12
      shorten: false
```
