### ISSUE TITLE
Getting 503 trying to get LinuxSecurity RSS feed, failed 1431 consecutive times

### ISSUE THREAD

**Issue by FingerlessGlov3s** [impredicative/irc-rss-feed-bot#74]
I have feed setup to get the following RSS feed every 30 minutes, but its failed 1431 consecutive times, if I exec curl inside the container after installing curl, the web url always returns fine. I wonder if I need a user agent override or something to that effect to get this working.

RSS: https://linuxsecurity.com/linuxsecurity_advisories.xml
Tag: 0.10.1

Current Config
```
LinuxSecurity:
      url: https://linuxsecurity.com/linuxsecurity_advisories.xml
      period: 0.5
      style:
        name:
          fg: green
      sub:
        title:
          pattern: '>$'
          repl: ''
```

My test to prove the docker container can get to the curl fine.
```
docker exec -it -u root ircbotsecurityfeed bash
apt update && apt install curl -y
curl https://linuxsecurity.com/linuxsecurity_advisories.xml works fine every time
```
